spring:
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null    #json返回不能为null
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.5/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell

